// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `Murmur.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Murmur;

/**
 * Retrieve ACLs and Groups on a channel.
 **/

public interface AMD_Server_getACL extends Ice.AMDCallback
{
    /**
     * ice_response indicates that
     * the operation completed successfully.
     * @param acls List of ACLs on the channel. This will include inherited ACLs.
     * @param inherit Does this channel inherit ACLs from the parent channel?
     **/
    void ice_response(ACL[] acls, Group[] groups, boolean inherit);
}
