// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `Murmur.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Murmur;

/**
 * Add a context callback. This is done per user, and will add a context menu action for the user.
 * 
 **/

public interface AMD_Server_addContextCallback extends Ice.AMDCallback
{
    /**
     * ice_response indicates that
     * the operation completed successfully.
     **/
    void ice_response();
}
