// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `Murmur.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Murmur;

/**
 * Fetch default configuraion. This returns the configuration items that were set in the configuration file, or
 * the built-in default. The individual servers will use these values unless they have been overridden in the
 * server specific configuration. The only special case is the port, which defaults to the value defined here +
 * the servers ID - 1 (so that virtual server #1 uses the defined port, server #2 uses port+1 etc).
 **/

public interface AMD_Meta_getDefaultConf extends Ice.AMDCallback
{
    /**
     * ice_response indicates that
     * the operation completed successfully.
     * @param __ret (return value) Default configuration of the servers.
     **/
    void ice_response(java.util.Map<java.lang.String, java.lang.String> __ret);
}
