// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `Murmur.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Murmur;

/**
 * Retrieve ACLs and Groups on a channel.
 **/

public abstract class Callback_Server_getACL extends Ice.TwowayCallback
{
    public abstract void response(ACL[] acls, Group[] groups, boolean inherit);
    public abstract void exception(Ice.UserException __ex);

    public final void __completed(Ice.AsyncResult __result)
    {
        ServerPrx __proxy = (ServerPrx)__result.getProxy();
        ACLListHolder acls = new ACLListHolder();
        GroupListHolder groups = new GroupListHolder();
        Ice.BooleanHolder inherit = new Ice.BooleanHolder();
        try
        {
            __proxy.end_getACL(acls, groups, inherit, __result);
        }
        catch(Ice.UserException __ex)
        {
            exception(__ex);
            return;
        }
        catch(Ice.LocalException __ex)
        {
            exception(__ex);
            return;
        }
        response(acls.value, groups.value, inherit.value);
    }
}
