// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `Murmur.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Murmur;

/**
 * Called when a channel is removed. The channel has already been removed, you can no longer use methods like {@link Server.getChannelState}
 **/

public abstract class Callback_ServerCallback_channelRemoved extends Ice.OnewayCallback
{
}
